import { RoomConfig } from '../../types'
import { ROOM_COLORS } from '../../constants'

export const ROOMS: RoomConfig[] = [
  // === Top row: Department offices ===
  {
    id: 'planogram',
    name: 'Planogram Dept',
    x: 0,
    y: 0,
    width: 30,
    height: 25,
    type: 'department',
    color: ROOM_COLORS.planogram,
    furniture: [
      // Dev workstations — left cluster with dual monitors, PC towers, gaming chairs
      { type: 'desk', x: 4, y: 5, width: 3, height: 2 },
      { type: 'dual_monitor', x: 4, y: 4, width: 3, height: 1 },
      { type: 'pc_tower', x: 7, y: 5, width: 1, height: 2 },
      { type: 'headphone_stand', x: 3, y: 5, width: 1, height: 1 },
      { type: 'gaming_chair', x: 5, y: 7, width: 1, height: 1 },
      { type: 'desk', x: 4, y: 10, width: 3, height: 2 },
      { type: 'dual_monitor', x: 4, y: 9, width: 3, height: 1 },
      { type: 'pc_tower', x: 7, y: 10, width: 1, height: 2 },
      { type: 'gaming_chair', x: 5, y: 12, width: 1, height: 1 },
      { type: 'desk', x: 4, y: 15, width: 3, height: 2 },
      { type: 'dual_monitor', x: 4, y: 14, width: 3, height: 1 },
      { type: 'pc_tower', x: 7, y: 15, width: 1, height: 2 },
      { type: 'gaming_chair', x: 5, y: 17, width: 1, height: 1 },
      // Dev workstations — right cluster
      { type: 'desk', x: 15, y: 5, width: 3, height: 2 },
      { type: 'dual_monitor', x: 15, y: 4, width: 3, height: 1 },
      { type: 'pc_tower', x: 18, y: 5, width: 1, height: 2 },
      { type: 'headphone_stand', x: 14, y: 5, width: 1, height: 1 },
      { type: 'gaming_chair', x: 16, y: 7, width: 1, height: 1 },
      { type: 'desk', x: 15, y: 10, width: 3, height: 2 },
      { type: 'dual_monitor', x: 15, y: 9, width: 3, height: 1 },
      { type: 'pc_tower', x: 18, y: 10, width: 1, height: 2 },
      { type: 'gaming_chair', x: 16, y: 12, width: 1, height: 1 },
      { type: 'desk', x: 15, y: 15, width: 3, height: 2 },
      { type: 'dual_monitor', x: 15, y: 14, width: 3, height: 1 },
      { type: 'pc_tower', x: 18, y: 15, width: 1, height: 2 },
      { type: 'gaming_chair', x: 16, y: 17, width: 1, height: 1 },
      // Cable management
      { type: 'cable_management', x: 4, y: 19, width: 4, height: 1 },
      { type: 'cable_management', x: 15, y: 19, width: 4, height: 1 },
      // Decor
      { type: 'plant', x: 2, y: 2, width: 1, height: 1 },
      { type: 'plant', x: 27, y: 2, width: 1, height: 1 },
      { type: 'trash_can', x: 10, y: 8, width: 1, height: 1 },
      { type: 'filing_cabinet', x: 22, y: 3, width: 1, height: 2 },
      { type: 'bookshelf', x: 24, y: 3, width: 2, height: 2 },
      { type: 'whiteboard', x: 10, y: 3, width: 4, height: 2 },
      { type: 'rug', x: 8, y: 12, width: 6, height: 4 },
      { type: 'desk_lamp', x: 3, y: 10, width: 1, height: 1 },
      { type: 'desk_lamp', x: 14, y: 15, width: 1, height: 1 },
      { type: 'coat_rack', x: 2, y: 20, width: 1, height: 2 },
      { type: 'coffee_cup', x: 6, y: 6, width: 1, height: 1 },
      // LED strip under desk edge
      { type: 'led_strip', x: 4, y: 7, width: 3, height: 1 },
      { type: 'led_strip', x: 15, y: 7, width: 3, height: 1 },
    ],
    deskPositions: [
      { x: 5, y: 7 },
      { x: 5, y: 12 },
      { x: 5, y: 17 },
      { x: 16, y: 7 },
      { x: 16, y: 12 },
      { x: 16, y: 17 },
    ],
    decorations: [
      { type: 'clock', x: 14, y: 0 },
      { type: 'window', x: 8, y: 0 },
      { type: 'window', x: 20, y: 0 },
      { type: 'poster', x: 26, y: 0 },
      // Wall shelving with books
      { type: 'wall_shelf', x: 10, y: 1 },
      { type: 'wall_shelf', x: 22, y: 1 },
      // String lights along top wall
      { type: 'string_lights', x: 4, y: 0 },
      { type: 'string_lights', x: 16, y: 0 },
      // Ceiling light cones
      { type: 'ceiling_light', x: 8, y: 1 },
      { type: 'ceiling_light', x: 20, y: 1 },
    ],
  },
  {
    id: 'mayor_office',
    name: "Mayor's Office",
    x: 30,
    y: 0,
    width: 10,
    height: 15,
    type: 'department',
    color: ROOM_COLORS.mayor_office,
    furniture: [
      // Executive desk with triple monitor command center
      { type: 'desk', x: 33, y: 5, width: 4, height: 2 },
      { type: 'triple_monitor', x: 33, y: 4, width: 4, height: 1 },
      { type: 'desk_lamp', x: 37, y: 5, width: 1, height: 1 },
      { type: 'cable_management', x: 33, y: 7, width: 4, height: 1 },
      // Executive bookshelves
      { type: 'bookshelf', x: 31, y: 1, width: 2, height: 2 },
      { type: 'bookshelf', x: 37, y: 1, width: 2, height: 2 },
      { type: 'plant', x: 31, y: 4, width: 1, height: 1 },
      { type: 'plant', x: 38, y: 4, width: 1, height: 1 },
      { type: 'filing_cabinet', x: 31, y: 10, width: 1, height: 2 },
      { type: 'couch', x: 33, y: 11, width: 4, height: 2 },
      { type: 'rug', x: 32, y: 6, width: 6, height: 4 },
      { type: 'coat_rack', x: 38, y: 10, width: 1, height: 2 },
      { type: 'coffee_cup', x: 35, y: 5, width: 1, height: 1 },
      { type: 'led_strip', x: 33, y: 7, width: 4, height: 1 },
    ],
    deskPositions: [{ x: 35, y: 7 }],
    decorations: [
      { type: 'sign', x: 34, y: 0, label: 'MAYOR' },
      { type: 'window', x: 32, y: 0 },
      { type: 'window', x: 37, y: 0 },
      { type: 'painting', x: 35, y: 0 },
      // Neon accent sign
      { type: 'neon_sign', x: 33, y: 1, color: '#ffd700' },
      // Ceiling light
      { type: 'ceiling_light', x: 35, y: 1 },
      // String lights
      { type: 'string_lights', x: 31, y: 0 },
    ],
  },
  {
    id: 'hallway',
    name: 'Main Hallway',
    x: 30,
    y: 15,
    width: 10,
    height: 30,
    type: 'hallway',
    color: ROOM_COLORS.hallway,
    furniture: [
      { type: 'plant', x: 32, y: 18, width: 1, height: 1 },
      { type: 'plant', x: 37, y: 18, width: 1, height: 1 },
      { type: 'water_cooler', x: 32, y: 25, width: 1, height: 1 },
      { type: 'plant', x: 37, y: 30, width: 1, height: 1 },
      { type: 'trash_can', x: 32, y: 35, width: 1, height: 1 },
      { type: 'coat_rack', x: 37, y: 38, width: 1, height: 2 },
    ],
    deskPositions: [],
    decorations: [
      { type: 'sign', x: 34, y: 15, label: 'HALL' },
      { type: 'clock', x: 36, y: 15 },
      // Ceiling lights along hallway
      { type: 'ceiling_light', x: 34, y: 16 },
      { type: 'ceiling_light', x: 34, y: 28 },
      { type: 'ceiling_light', x: 34, y: 38 },
    ],
  },
  {
    id: 'alc_ai',
    name: 'ALC AI Dept',
    x: 40,
    y: 0,
    width: 30,
    height: 25,
    type: 'department',
    color: ROOM_COLORS.alc_ai,
    furniture: [
      // Dev workstations — left cluster
      { type: 'desk', x: 44, y: 5, width: 3, height: 2 },
      { type: 'dual_monitor', x: 44, y: 4, width: 3, height: 1 },
      { type: 'pc_tower', x: 47, y: 5, width: 1, height: 2 },
      { type: 'headphone_stand', x: 43, y: 5, width: 1, height: 1 },
      { type: 'gaming_chair', x: 45, y: 7, width: 1, height: 1 },
      { type: 'desk', x: 44, y: 10, width: 3, height: 2 },
      { type: 'dual_monitor', x: 44, y: 9, width: 3, height: 1 },
      { type: 'pc_tower', x: 47, y: 10, width: 1, height: 2 },
      { type: 'gaming_chair', x: 45, y: 12, width: 1, height: 1 },
      { type: 'desk', x: 44, y: 15, width: 3, height: 2 },
      { type: 'dual_monitor', x: 44, y: 14, width: 3, height: 1 },
      { type: 'pc_tower', x: 47, y: 15, width: 1, height: 2 },
      { type: 'gaming_chair', x: 45, y: 17, width: 1, height: 1 },
      // Dev workstations — right cluster
      { type: 'desk', x: 55, y: 5, width: 3, height: 2 },
      { type: 'dual_monitor', x: 55, y: 4, width: 3, height: 1 },
      { type: 'pc_tower', x: 58, y: 5, width: 1, height: 2 },
      { type: 'headphone_stand', x: 54, y: 5, width: 1, height: 1 },
      { type: 'gaming_chair', x: 56, y: 7, width: 1, height: 1 },
      { type: 'desk', x: 55, y: 10, width: 3, height: 2 },
      { type: 'dual_monitor', x: 55, y: 9, width: 3, height: 1 },
      { type: 'pc_tower', x: 58, y: 10, width: 1, height: 2 },
      { type: 'gaming_chair', x: 56, y: 12, width: 1, height: 1 },
      { type: 'desk', x: 55, y: 15, width: 3, height: 2 },
      { type: 'dual_monitor', x: 55, y: 14, width: 3, height: 1 },
      { type: 'pc_tower', x: 58, y: 15, width: 1, height: 2 },
      { type: 'gaming_chair', x: 56, y: 17, width: 1, height: 1 },
      // Cable management
      { type: 'cable_management', x: 44, y: 19, width: 4, height: 1 },
      { type: 'cable_management', x: 55, y: 19, width: 4, height: 1 },
      // Decor
      { type: 'plant', x: 42, y: 2, width: 1, height: 1 },
      { type: 'plant', x: 67, y: 2, width: 1, height: 1 },
      { type: 'server_rack', x: 62, y: 3, width: 1, height: 3 },
      { type: 'whiteboard', x: 50, y: 3, width: 4, height: 2 },
      { type: 'trash_can', x: 50, y: 18, width: 1, height: 1 },
      { type: 'filing_cabinet', x: 64, y: 3, width: 1, height: 2 },
      { type: 'desk_lamp', x: 43, y: 10, width: 1, height: 1 },
      { type: 'desk_lamp', x: 54, y: 15, width: 1, height: 1 },
      { type: 'rug', x: 48, y: 12, width: 6, height: 4 },
      { type: 'coat_rack', x: 42, y: 20, width: 1, height: 2 },
      { type: 'coffee_cup', x: 46, y: 6, width: 1, height: 1 },
      { type: 'led_strip', x: 44, y: 7, width: 3, height: 1 },
      { type: 'led_strip', x: 55, y: 7, width: 3, height: 1 },
    ],
    deskPositions: [
      { x: 45, y: 7 },
      { x: 45, y: 12 },
      { x: 45, y: 17 },
      { x: 56, y: 7 },
      { x: 56, y: 12 },
      { x: 56, y: 17 },
    ],
    decorations: [
      { type: 'window', x: 48, y: 0 },
      { type: 'window', x: 60, y: 0 },
      { type: 'clock', x: 54, y: 0 },
      { type: 'poster', x: 66, y: 0 },
      // Wall shelves with books
      { type: 'wall_shelf', x: 50, y: 1 },
      { type: 'wall_shelf', x: 62, y: 1 },
      // String lights
      { type: 'string_lights', x: 44, y: 0 },
      { type: 'string_lights', x: 56, y: 0 },
      // Ceiling lights
      { type: 'ceiling_light', x: 48, y: 1 },
      { type: 'ceiling_light', x: 60, y: 1 },
      // Neon accent
      { type: 'neon_sign', x: 52, y: 1, color: '#44ddff' },
    ],
  },
  {
    id: 'arcade_dept',
    name: 'Arcade Dept',
    x: 70,
    y: 0,
    width: 30,
    height: 25,
    type: 'department',
    color: ROOM_COLORS.arcade,
    furniture: [
      // Dev workstations — left cluster
      { type: 'desk', x: 74, y: 5, width: 3, height: 2 },
      { type: 'dual_monitor', x: 74, y: 4, width: 3, height: 1 },
      { type: 'pc_tower', x: 77, y: 5, width: 1, height: 2 },
      { type: 'headphone_stand', x: 73, y: 5, width: 1, height: 1 },
      { type: 'gaming_chair', x: 75, y: 7, width: 1, height: 1 },
      { type: 'desk', x: 74, y: 10, width: 3, height: 2 },
      { type: 'dual_monitor', x: 74, y: 9, width: 3, height: 1 },
      { type: 'pc_tower', x: 77, y: 10, width: 1, height: 2 },
      { type: 'gaming_chair', x: 75, y: 12, width: 1, height: 1 },
      // Dev workstations — right cluster
      { type: 'desk', x: 85, y: 5, width: 3, height: 2 },
      { type: 'dual_monitor', x: 85, y: 4, width: 3, height: 1 },
      { type: 'pc_tower', x: 88, y: 5, width: 1, height: 2 },
      { type: 'headphone_stand', x: 84, y: 5, width: 1, height: 1 },
      { type: 'gaming_chair', x: 86, y: 7, width: 1, height: 1 },
      { type: 'desk', x: 85, y: 10, width: 3, height: 2 },
      { type: 'dual_monitor', x: 85, y: 9, width: 3, height: 1 },
      { type: 'pc_tower', x: 88, y: 10, width: 1, height: 2 },
      { type: 'gaming_chair', x: 86, y: 12, width: 1, height: 1 },
      // Cable management
      { type: 'cable_management', x: 74, y: 14, width: 4, height: 1 },
      { type: 'cable_management', x: 85, y: 14, width: 4, height: 1 },
      // Decor
      { type: 'plant', x: 72, y: 2, width: 1, height: 1 },
      { type: 'plant', x: 97, y: 2, width: 1, height: 1 },
      { type: 'server_rack', x: 92, y: 3, width: 1, height: 3 },
      { type: 'bookshelf', x: 94, y: 3, width: 2, height: 2 },
      { type: 'whiteboard', x: 80, y: 3, width: 4, height: 2 },
      { type: 'rug', x: 78, y: 12, width: 6, height: 4 },
      { type: 'desk_lamp', x: 73, y: 10, width: 1, height: 1 },
      { type: 'desk_lamp', x: 84, y: 10, width: 1, height: 1 },
      { type: 'coat_rack', x: 72, y: 20, width: 1, height: 2 },
      { type: 'coffee_cup', x: 76, y: 6, width: 1, height: 1 },
      { type: 'led_strip', x: 74, y: 7, width: 3, height: 1 },
      { type: 'led_strip', x: 85, y: 7, width: 3, height: 1 },
    ],
    deskPositions: [
      { x: 75, y: 7 },
      { x: 75, y: 12 },
      { x: 86, y: 7 },
      { x: 86, y: 12 },
    ],
    decorations: [
      { type: 'window', x: 78, y: 0 },
      { type: 'window', x: 90, y: 0 },
      { type: 'clock', x: 84, y: 0 },
      // Wall shelves
      { type: 'wall_shelf', x: 80, y: 1 },
      { type: 'wall_shelf', x: 96, y: 1 },
      // String lights (extra festive for arcade)
      { type: 'string_lights', x: 74, y: 0 },
      { type: 'string_lights', x: 82, y: 0 },
      { type: 'string_lights', x: 90, y: 0 },
      // Neon signs (arcade vibe)
      { type: 'neon_sign', x: 76, y: 1, color: '#ff44aa' },
      { type: 'neon_sign', x: 92, y: 1, color: '#44ff88' },
      // Ceiling lights
      { type: 'ceiling_light', x: 80, y: 1 },
      { type: 'ceiling_light', x: 88, y: 1 },
    ],
  },
  // === Bottom row ===
  {
    id: 'breakroom',
    name: 'Break Room',
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    type: 'breakroom',
    color: ROOM_COLORS.breakroom,
    furniture: [
      { type: 'table', x: 5, y: 30, width: 3, height: 2 },
      { type: 'chair', x: 4, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 6, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 8, y: 32, width: 1, height: 1 },
      { type: 'table', x: 12, y: 30, width: 3, height: 2 },
      { type: 'chair', x: 11, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 13, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 15, y: 32, width: 1, height: 1 },
      { type: 'vending_machine', x: 3, y: 27, width: 1, height: 2 },
      { type: 'coffee_machine', x: 5, y: 27, width: 1, height: 1 },
      { type: 'couch', x: 8, y: 38, width: 4, height: 2 },
      { type: 'trash_can', x: 16, y: 27, width: 1, height: 1 },
      { type: 'coffee_cup', x: 6, y: 30, width: 1, height: 1 },
      { type: 'coffee_cup', x: 13, y: 30, width: 1, height: 1 },
      { type: 'coat_rack', x: 17, y: 38, width: 1, height: 2 },
    ],
    deskPositions: [],
    decorations: [
      { type: 'sign', x: 8, y: 25, label: 'BREAK' },
      { type: 'poster', x: 2, y: 25 },
      { type: 'clock', x: 10, y: 25 },
      // String lights for cozy vibe
      { type: 'string_lights', x: 4, y: 25 },
      { type: 'string_lights', x: 14, y: 25 },
      // Ceiling lights
      { type: 'ceiling_light', x: 8, y: 26 },
      // Neon coffee sign
      { type: 'neon_sign', x: 6, y: 26, color: '#ff8844' },
    ],
  },
  {
    id: 'meeting_room',
    name: 'Meeting Room',
    x: 20,
    y: 25,
    width: 18,
    height: 20,
    type: 'meeting_room',
    color: ROOM_COLORS.meeting_room,
    furniture: [
      { type: 'meeting_table', x: 24, y: 31, width: 8, height: 4 },
      { type: 'chair', x: 23, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 23, y: 34, width: 1, height: 1 },
      { type: 'chair', x: 33, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 33, y: 34, width: 1, height: 1 },
      { type: 'chair', x: 26, y: 36, width: 1, height: 1 },
      { type: 'chair', x: 28, y: 36, width: 1, height: 1 },
      { type: 'chair', x: 30, y: 36, width: 1, height: 1 },
      { type: 'chair', x: 26, y: 30, width: 1, height: 1 },
      { type: 'chair', x: 28, y: 30, width: 1, height: 1 },
      { type: 'chair', x: 30, y: 30, width: 1, height: 1 },
      { type: 'projector_screen', x: 24, y: 27, width: 8, height: 2 },
      { type: 'plant', x: 22, y: 27, width: 1, height: 1 },
      { type: 'plant', x: 35, y: 27, width: 1, height: 1 },
      { type: 'whiteboard', x: 34, y: 27, width: 3, height: 2 },
      { type: 'coat_rack', x: 22, y: 40, width: 1, height: 2 },
      { type: 'coffee_cup', x: 26, y: 31, width: 1, height: 1 },
    ],
    deskPositions: [],
    decorations: [
      { type: 'sign', x: 27, y: 25, label: 'MEET' },
      { type: 'clock', x: 30, y: 25 },
      // Ceiling lights for meeting room
      { type: 'ceiling_light', x: 26, y: 26 },
      { type: 'ceiling_light', x: 32, y: 26 },
    ],
  },
  {
    id: 'smoke_area',
    name: 'Smoke Area',
    x: 38,
    y: 25,
    width: 16,
    height: 20,
    type: 'smoke_area',
    color: ROOM_COLORS.smoke_area,
    furniture: [
      { type: 'ashtray', x: 42, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 41, y: 33, width: 1, height: 1 },
      { type: 'chair', x: 43, y: 33, width: 1, height: 1 },
      { type: 'ashtray', x: 48, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 47, y: 33, width: 1, height: 1 },
      { type: 'chair', x: 49, y: 33, width: 1, height: 1 },
      { type: 'trash_can', x: 40, y: 27, width: 1, height: 1 },
      { type: 'plant', x: 51, y: 27, width: 1, height: 1 },
    ],
    deskPositions: [],
    decorations: [
      { type: 'sign', x: 44, y: 25, label: 'SMOKE' },
    ],
  },
  {
    id: 'bathroom',
    name: 'Bathroom',
    x: 54,
    y: 25,
    width: 14,
    height: 20,
    type: 'bathroom',
    color: ROOM_COLORS.bathroom,
    furniture: [
      { type: 'toilet', x: 57, y: 29, width: 1, height: 1 },
      { type: 'toilet', x: 60, y: 29, width: 1, height: 1 },
      { type: 'toilet', x: 63, y: 29, width: 1, height: 1 },
      { type: 'toilet', x: 57, y: 35, width: 1, height: 1 },
      { type: 'toilet', x: 60, y: 35, width: 1, height: 1 },
      { type: 'toilet', x: 63, y: 35, width: 1, height: 1 },
      { type: 'trash_can', x: 56, y: 27, width: 1, height: 1 },
    ],
    deskPositions: [],
    decorations: [
      { type: 'sign', x: 59, y: 25, label: 'WC' },
    ],
  },
  {
    id: 'play_area',
    name: 'Play Area',
    x: 68,
    y: 25,
    width: 32,
    height: 20,
    type: 'play_area',
    color: ROOM_COLORS.play_area,
    furniture: [
      { type: 'arcade_machine', x: 72, y: 28, width: 1, height: 2 },
      { type: 'arcade_machine', x: 75, y: 28, width: 1, height: 2 },
      { type: 'arcade_machine', x: 78, y: 28, width: 1, height: 2 },
      { type: 'arcade_machine', x: 81, y: 28, width: 1, height: 2 },
      { type: 'ping_pong', x: 85, y: 30, width: 6, height: 4 },
      { type: 'couch', x: 72, y: 38, width: 4, height: 2 },
      { type: 'couch', x: 80, y: 38, width: 4, height: 2 },
      { type: 'table', x: 90, y: 32, width: 3, height: 2 },
      { type: 'chair', x: 89, y: 34, width: 1, height: 1 },
      { type: 'chair', x: 93, y: 34, width: 1, height: 1 },
      { type: 'plant', x: 70, y: 27, width: 1, height: 1 },
      { type: 'plant', x: 97, y: 27, width: 1, height: 1 },
      { type: 'vending_machine', x: 95, y: 28, width: 1, height: 2 },
    ],
    deskPositions: [],
    decorations: [
      { type: 'sign', x: 82, y: 25, label: 'PLAY' },
      { type: 'poster', x: 70, y: 25 },
      { type: 'poster', x: 96, y: 25 },
      // String lights (festive play area)
      { type: 'string_lights', x: 72, y: 25 },
      { type: 'string_lights', x: 80, y: 25 },
      { type: 'string_lights', x: 88, y: 25 },
      // Neon signs (arcade/play vibe)
      { type: 'neon_sign', x: 74, y: 26, color: '#ff44aa' },
      { type: 'neon_sign', x: 94, y: 26, color: '#44ff88' },
      // Ceiling lights
      { type: 'ceiling_light', x: 78, y: 26 },
      { type: 'ceiling_light', x: 90, y: 26 },
    ],
  },
  // === Polecat Yard ===
  {
    id: 'polecat_yard',
    name: 'Polecat Yard',
    x: 0,
    y: 46,
    width: 30,
    height: 14,
    type: 'polecat_yard',
    color: ROOM_COLORS.polecat_yard,
    furniture: [
      // Basketball hoop area
      { type: 'ping_pong', x: 4, y: 50, width: 4, height: 3 },
      // Bench / hangout area
      { type: 'couch', x: 12, y: 49, width: 4, height: 2 },
      { type: 'table', x: 18, y: 49, width: 3, height: 2 },
      { type: 'chair', x: 17, y: 51, width: 1, height: 1 },
      { type: 'chair', x: 21, y: 51, width: 1, height: 1 },
      // Coffee / vending
      { type: 'coffee_machine', x: 24, y: 48, width: 1, height: 1 },
      { type: 'vending_machine', x: 26, y: 48, width: 1, height: 2 },
      // Ashtray corner
      { type: 'ashtray', x: 4, y: 55, width: 1, height: 1 },
      { type: 'chair', x: 3, y: 56, width: 1, height: 1 },
      { type: 'chair', x: 5, y: 56, width: 1, height: 1 },
      // Trash
      { type: 'trash_can', x: 27, y: 57, width: 1, height: 1 },
    ],
    deskPositions: [],
    decorations: [
      { type: 'sign', x: 12, y: 46, label: 'YARD' },
    ],
  },
]

/** Get doorway positions connecting rooms */
export function getDoorways(): { x: number; y: number; roomA: string; roomB: string }[] {
  return [
    // Mayor's office <-> Hallway
    { x: 35, y: 15, roomA: 'mayor_office', roomB: 'hallway' },
    // Planogram <-> Hallway (through the side)
    { x: 30, y: 20, roomA: 'planogram', roomB: 'hallway' },
    // Hallway <-> ALC AI
    { x: 40, y: 20, roomA: 'hallway', roomB: 'alc_ai' },
    // ALC AI <-> Arcade Dept
    { x: 70, y: 12, roomA: 'alc_ai', roomB: 'arcade_dept' },
    // Hallway -> Break Room
    { x: 15, y: 25, roomA: 'breakroom', roomB: 'hallway' },
    // Hallway -> Meeting Room
    { x: 30, y: 35, roomA: 'hallway', roomB: 'meeting_room' },
    // Meeting Room <-> Smoke Area
    { x: 38, y: 35, roomA: 'meeting_room', roomB: 'smoke_area' },
    // Smoke Area <-> Bathroom
    { x: 54, y: 35, roomA: 'smoke_area', roomB: 'bathroom' },
    // Bathroom <-> Play Area
    { x: 68, y: 35, roomA: 'bathroom', roomB: 'play_area' },
    // Breakroom <-> Meeting Room
    { x: 20, y: 35, roomA: 'breakroom', roomB: 'meeting_room' },
    // Breakroom <-> Polecat Yard
    { x: 10, y: 45, roomA: 'breakroom', roomB: 'polecat_yard' },
  ]
}
